# This feature is in Beta.

# Please report any bugs to support@astronomer.io

# NOTE: If putting a dict in conn_extra, please wrap in single quotes.

# More details you can find https://github.com/astronomer/docs/blob/main/v0.10/cli-airflow-configuration.md

airflow:
  connections:
    - conn_id: local_postgres
      conn_type: postgres
      conn_host: example.db.example.com
      conn_schema: schema
      conn_login: username
      conn_password: password
      conn_port: 5432
      conn_extra: '{"extra__snowflake__account": "snowflake_local", "extra__snowflake__database": "snowflake_db", "extra__snowflake__insecure_mode": "False", "extra__snowflake__region": "us-east"}'
    - conn_id: david_snowflake
      conn_type: snowflake
      conn_host: https://gp21411.us-east-1.snowflakecomputing.com
      conn_schema: DAVIDKOENITZER
      conn_login: DAVIDKOENITZER
      conn_password: Snow900flake
      conn_port: 443
      conn_extra:
        extra__snowflake__account: gp21411.us-east-1
        extra__snowflake__database: SANDBOX
        extra__snowflake__insecure_mode: 'False'
  pools:
    - pool_name: subdag_limit
      pool_slot: 3
      pool_description:
  variables:
    - variable_name: myvar
      variable_value: myval