name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        ./astrocloud deploy ckzcyxeax19441fxijp7hsmo6