name: Astronomer CI - Deploy code to Astro

on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: cle4p0fdt325082f05nco4rt6pu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Deploy to Astro
      shell: bash
      run: |
        ./astro context switch astronomer-dev.io
        ./astro deploy $DEPLOYMENT_ID