name: CI/CD

on:
  push:
    branches:
      - main

env:
  ## Sets environment variable
  ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
  ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        brew install astronomer/cloud/astrocloud@1.1.0-test
        astrocloud deploy ckzcyxeax19441fxijp7hsmo6