name: Astronomer CI - Create deployment preview

on:
  create:
    branches:
    - "**"

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: cleyelyk717631j1e9wihcrkx

jobs:
  create-deployment-preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: get branch name
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
    - name: Create and Deploy to Deployment Preview
      shell: bash
      run: |
        # install the Astro CLI
        # curl -sSL https://install.astronomer.io | sudo bash -s

        ./astro context switch astronomer-dev.io

        # get deployment preview name
        DEPLOYMENT_NAME="$(./astro deployment inspect $DEPLOYMENT_ID --key configuration.name)"
        BRANCH_DEPLOYMENT_NAME=${{ env.BRANCH_NAME }}_$DEPLOYMENT_NAME
        BRANCH_DEPLOYMENT_NAME="${BRANCH_DEPLOYMENT_NAME// /_}"

        # Create template of deployment to be copied with
        ./astro deployment inspect $DEPLOYMENT_ID --template > deployment-preview-template.yaml # autmatically creates deployment-preview-template.yaml file

        # Add name to deployment template file
        sed -i "s|  name:.*|  name: ${BRANCH_DEPLOYMENT_NAME}|g"  deployment-preview-template.yaml
        
        # Create new deploymeent preview based on the deployment template file
        ./astro deployment create --deployment-file deployment-preview-template.yaml

        # Deploy new code to the deployment preview 
        ./astro deploy -n $BRANCH_DEPLOYMENT_NAME