name: Astronomer CI - Delete Deployment Preview

on:
  delete:
    branches:
    - "**"
env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: cle4p6y241451300jl3l0r88m

jobs:
  create-deployment-preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Create and Deploy to Deployment Preview
      shell: bash
      run: |
        # install the Astro CLI
        # curl -sSL https://install.astronomer.io | sudo bash -s

        ./astro context switch astronomer-dev.io

        # ./astro workspace switch "Onboarding - Customer Success"

        # get deployment preview name
        DEPLOYMENT_NAME="$(./astro deployment inspect $DEPLOYMENT_ID --key configuration.name)"
        BRANCH_DEPLOYMENT_NAME=${{ github.event.ref }}_$DEPLOYMENT_NAME
        BRANCH_DEPLOYMENT_NAME="${BRANCH_DEPLOYMENT_NAME// /_}"

        # delete branch deployment
        ./astro deployment delete -n $BRANCH_DEPLOYMENT_NAME -f