name: Astronomer CI - Deploy code to Preview

on:
  push:
    branches:
    - '**'
    - '!main' 

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Deployment Preivew
      uses: astronomer/deploy-action@v0.3
      with:
        action: deploy-deployment-preview
        deployment-name: "test deployment"