name: Astronomer CI - Deploy code

on:
  pull_request:
    branches:
      - main
env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: cle4p0fdt325082f05nco4rt6pu

jobs:
  deploy-to-preview:
    uns-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Deploy to Deployment Preview
      shell: bash
      run: |
        # get deployment preview name
        DEPLOYMENT_NAME="$(./astro deployment inspect $DEPLOYMENT_ID --key configuration.name)"
        BRANCH_DEPLOYMENT_NAME=${GITHUB_HEAD_REF##*/}_$DEPLOYMENT_NAME
        BRANCH_DEPLOYMENT_NAME="${BRANCH_DEPLOYMENT_NAME// /_}"

        # Deploy new code to the deployment preview 
        ./astro deploy -n $BRANCH_DEPLOYMENT_NAME