name: Astronomer CI - Deploy to Deployment

on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Deploy to Deployment 
      shell: bash
      run: |
        # install the Astro CLI
        curl -sSL https://install.astronomer.io | sudo bash -s v1.19.3

        # deploy code
        astro deploy -n "test deployment"

