name: Astronomer CI - Test Create

on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Install Astro CLI"
      shell: bash
      run: |
        curl -sSL https://install.astronomer.io | sudo bash -s -- v1.17.1
    - name: Deploy to Deployment
      shell: bash
      run: |
        astro deployment create --deployment-file deployment.yaml
