name: Astronomer CI - Deploy code to Preview

on:
  push:
    branches:
      - "**"
      - "!main"

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_ACTIONS env var
        run: echo "GITHUB_ACTIONS=${GITHUB_ACTIONS}"
      - name: Deploy to Deployment Preivew
        uses: astronomer/deploy-action@dbt-deploy
        with:
          action: deploy-deployment-preview
          deployment-name: neel-test
