name: Astronomer CI - Deploy code to Preview

on:
  pull_request:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: cleys4bnf00732z1r7eks5nqw

jobs:
  deploy-to-preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Deploy to Deployment Preview
      shell: bash
      run: |
        ./astro context switch astronomer-dev.io
        # ./astro workspace switch "Onboarding - Customer Success"

        # get deployment preview name
        DEPLOYMENT_NAME="$(./astro deployment inspect $DEPLOYMENT_ID --key configuration.name)"
        BRANCH_DEPLOYMENT_NAME=${GITHUB_HEAD_REF##*/}_$DEPLOYMENT_NAME
        BRANCH_DEPLOYMENT_NAME="${BRANCH_DEPLOYMENT_NAME// /_}"

        # Deploy new code to the deployment preview
        ./astro deploy -n $BRANCH_DEPLOYMENT_NAME