name: Astronomer CI - Create deployment preview

on:
  create:
    branches:
      - "**"
      - "!main"

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Deployment Preview
        uses: astronomer/deploy-action@dbt-deploy
        with:
          action: create-deployment-preview
          deployment-name: neel-test
