name: Astronomer CI - Deploy to Deployment

on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history
        clean: false
    - name: Debug Output
      run: |
        git branch -a
        git log --oneline -5
        git fetch origin main
        git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
    - name: Deploy to Deployment 
      uses: astronomer/deploy-action@v0.5
