name: Astronomer CI - Deploy code (Multiple Branches)

on:
  push:
    branches: [dev, main]

jobs:
  dev-push:
    if: github.ref == 'refs/heads/dev'
    env:
      ## Sets DEV Deployment API credential as an environment variable
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.6
      with:
        deployment-name: dev
  prod-push:
    if: github.ref == 'refs/heads/main'
    env:
      ## Sets Prod Deployment API credential as an environment variable
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.6
      with:
        deployment-name: prod
