name: Deploy (checkdeployaction)
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  job-1:
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |

          sudo apt-get install jq

          # we need to pre-install the CLI to set the context
          curl -sSL https://install.astronomer.io | sudo bash -s

      - name: Set CLI context
        run: astro context switch astronomer-stage.io

      - name: Print GITHUB_ACTIONS env var
        run: echo "GITHUB_ACTIONS=${GITHUB_ACTIONS}"

      - name: Deploy DAGs/Image
        uses: astronomer/deploy-action@fix/rebase-force-push
        with:
          deployment-name: neel-test
          deploy-type: infer
          workspace: ${{ secrets.WORKSPACE_ID }}
