name: Deploy (checkdeployaction)
on:
  push:
    branches:
      - main

jobs:
  prod-astronomer:
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_ACTIONS env var
        run: echo "GITHUB_ACTIONS=${GITHUB_ACTIONS}"
      # - name: DBT Deploy
      #   uses: astronomer/deploy-action@checkout-submodule
      #   with:
      #     action: dbt-deploy
      #     deployment-name: neel-test-1
      #     root-folder: dbt/
      #     mount-path: /dbt
      #     workspace: ${{ secrets.WORKSPACE_ID }}
      #     checkout-submodules: true
      - name: Deploy DAGs/Image
        uses: astronomer/deploy-action@checkout-submodule
        with:
          root-folder: astro-project/
          deployment-name: neel-test-1
          workspace: ${{ secrets.WORKSPACE_ID }}
          checkout-submodules: recursive
