name: Deploy (checkdeployaction)
on:
  push:
    branches:
      - main
jobs:
  prod-astronomer:
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        uses: astronomer/deploy-action@v0.6
        with:
          deployment-name: prod
