name: Deploy (checkdeployaction)
on:
  push:
    branches:
      - main
jobs:
  prod-astronomer:
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        if: ${{ inputs.checkout }} == true
        with:
          fetch-depth: 0  # Fetch all history
          ref: ${{ github.event.after }}
          clean: false
      - name: Deploy Requirements.txt, DAG, includes and plugins to Astro
        uses: astronomer/deploy-action@v0.5
        with:
          deployment-name: david test
          checkout: false
