name: Deploy (checkdeployaction)
on:
  push:
    branches:
      - main
jobs:
  prod-astronomer:
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        uses: astronomer/deploy-action@feature/wake-up-dev-deployment
        with:
          deployment-name: prod
